### ISSUE TITLE
Create the Figma design prototype

### ISSUE THREAD

**Issue by infinitybl** [bhagatr11/Reunity#2]
# Create the Figma design prototype
We will make make the design prototypes for each of the webpages using Figma, including the
home page, the login page, the user profile page, the news feed page, etc. This will be the first
step in creating the user interface as we need to have a clear layout of our design before coding
it in React.js. Anurag Sake and Raiyan Afiz will be working as a pair on the design prototype.

**Comment by bhagatr11** [comment]
Added .PDF file of our prototype which was made using Figma
